import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home({data}) {
  console.log('data', data)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <Link href="about">about</Link>
      {/* <Image src='/vercel.svg' fill /> */}
      {data.map((dtd, i)=>(
        <Link key={i} href={`detail/${dtd.id}`}><p>{dtd.title}</p></Link>
        ))}

        <style jsx>
        {
          `
          p{
            color: red;
          }
          `
        }
        </style>
      </main>
    </>
  )
}

export const getStaticProps = async ()=>{
  const data = await fetch('https://jsonplaceholder.typicode.com/posts').then(res=> res.json())
  return{
    props: {
      data
    }
  }
}
